steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - --trigger-http
      - --source=.
      - --entry-point=app
      - --runtime=nodejs10
      - turnio-opensrp
